[package]
name = "es01"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
elasticsearch = "8.5.0-alpha.1"
serde = "1.0.209"
serde_json = "1.0.127"
tokio = { version = "1", features = ["full"] }
